In [23]:
# ----- ALL NECESSARY LIBRARIES ----- #
import numpy as np 
import modern_robotics as mr 
import math as mt 

In [24]:
M01 = [[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0.089159], [0, 0, 0, 1]]
M12 = [[0, 0, 1, 0.28], [0, 1, 0, 0.13585], [-1, 0, 0, 0], [0, 0, 0, 1]]
M23 = [[1, 0, 0, 0], [0, 1, 0, -0.1197], [0, 0, 1, 0.395], [0, 0, 0, 1]]
M34 = [[0, 0, 1, 0], [0, 1, 0, 0], [-1, 0, 0, 0.14225], [0, 0, 0, 1]]
M45 = [[1, 0, 0, 0], [0, 1, 0, 0.093], [0, 0, 1, 0], [0, 0, 0, 1]]
M56 = [[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0.09465], [0, 0, 0, 1]]
M67 = [[1, 0, 0, 0], [0, 0, 1, 0.0823], [0, -1, 0, 0], [0, 0, 0, 1]]
G1 = np.diag([0.010267495893, 0.010267495893,  0.00666, 3.7, 3.7, 3.7])
G2 = np.diag([0.22689067591, 0.22689067591, 0.0151074, 8.393, 8.393, 8.393])
G3 = np.diag([0.049443313556, 0.049443313556, 0.004095, 2.275, 2.275, 2.275])
G4 = np.diag([0.111172755531, 0.111172755531, 0.21942, 1.219, 1.219, 1.219])
G5 = np.diag([0.111172755531, 0.111172755531, 0.21942, 1.219, 1.219, 1.219])
G6 = np.diag([0.0171364731454, 0.0171364731454, 0.033822, 0.1879, 0.1879, 0.1879])
Glist = [G1, G2, G3, G4, G5, G6]
Mlist = [M01, M12, M23, M34, M45, M56, M67] 
Slist = [[0,         0,         0,         0,        0,        0],
        [0,         1,         1,         1,        0,        1],
        [1,         0,         0,         0,       -1,        0],
        [0, -0.089159, -0.089159, -0.089159, -0.10915, 0.005491],
        [0,         0,         0,         0,  0.81725,        0],
        [0,         0,     0.425,   0.81725,        0,  0.81725]]

In [25]:
# 1. Define your states
theta = np.array([0, np.pi/6, np.pi/4, np.pi/3, np.pi/2, 2*np.pi/3])
d_theta = np.array([0.2, 0.2, 0.2, 0.2, 0.2, 0.2])
dd_theta = np.array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1])

# 2. Define external forces
g = np.array([0, 0, -9.81])
F_tip = np.array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1])

In [26]:
# 3. Inverse Dynamics (Brings back your joint torques calculation)
torques = mr.InverseDynamics(theta, d_theta, dd_theta, g, F_tip, Mlist, Glist, Slist)
print("Your Joint Torques are:")
print(np.round(torques, 5))
print("\n" + "-"*50 + "\n")

# 4. Mass Matrix
mass_matrix = mr.MassMatrix(theta, Mlist, Glist, Slist)
print("Your Mass Matrix M(theta) is:")
print(np.round(mass_matrix, 5))
print("\n" + "-"*50 + "\n")

Your Joint Torques are:
[ 1.27700e-02 -4.11477e+01 -3.78093e+00  3.23100e-02  3.69500e-02
  1.03370e-01]

--------------------------------------------------

Your Mass Matrix M(theta) is:
[[ 2.19777  0.27228  0.06803 -0.00648  0.17022 -0.01212]
 [ 0.27228  3.55369  1.31041  0.24034 -0.00723  0.     ]
 [ 0.06803  1.31041  0.83725  0.24764 -0.00723  0.     ]
 [-0.00648  0.24034  0.24764  0.25368 -0.00723  0.     ]
 [ 0.17022 -0.00723 -0.00723 -0.00723  0.24073  0.     ]
 [-0.01212  0.       0.       0.       0.       0.01714]]

--------------------------------------------------



In [27]:
# 5. Velocity Quadratic Forces - c(theta, d_theta)
Vel_quad_forces = mr.VelQuadraticForces(theta, d_theta, Mlist, Glist, Slist)
print("Velocity Quadratic Force Matrix:")
print(np.round(Vel_quad_forces, 5))
print("\n" + "-"*50 + "\n")

# 6. Gravity Forces - g(theta)
Gravity_force = mr.GravityForces(theta, g, Mlist, Glist, Slist)
print("Gravity Force Matrix:")
print(np.round(Gravity_force, 5))
print("\n" + "-"*50 + "\n")



Velocity Quadratic Force Matrix:
[-0.11745 -0.01071  0.03165 -0.01477  0.02339  0.00287]

--------------------------------------------------

Gravity Force Matrix:
[  0.      -41.59673  -3.93591   0.12337   0.        0.     ]

--------------------------------------------------



In [28]:
# 7. End Effector Forces - J^T(theta) * F_tip
End_eff_force = mr.EndEffectorForces(theta, F_tip, Mlist, Glist, Slist)
print("End Effector Force Matrix:")
print(np.round(End_eff_force, 5))
print("\n" + "-"*50 + "\n")

# 8. Forward Dynamics (Takes the 'torques' variable calculated in step 3)
forward_dynamics = mr.ForwardDynamics(theta, d_theta, torques, g, F_tip, Mlist, Glist, Slist)
print("Forward Dynamics (dd_theta result):")
print(np.round(forward_dynamics, 5))

End Effector Force Matrix:
[-0.13875 -0.07721 -0.12229 -0.14908 -0.02536  0.1    ]

--------------------------------------------------

Forward Dynamics (dd_theta result):
[0.1 0.1 0.1 0.1 0.1 0.1]
